/**
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.validation;

import de.hub.modsoft.twittersearch.xtext.validation.AbstractTwitterSearchValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TwitterSearchValidator extends AbstractTwitterSearchValidator {
}
