/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TwitterSearchAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/hub/modsoft/twittersearch/xtext/parser/antlr/internal/InternalTwitterSearch.tokens");
	}
}
