/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.hub.modsoft.twittersearch.xtext.services.TwitterSearchGrammarAccess;

public class TwitterSearchParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TwitterSearchGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.hub.modsoft.twittersearch.xtext.parser.antlr.internal.InternalTwitterSearchParser createParser(XtextTokenStream stream) {
		return new de.hub.modsoft.twittersearch.xtext.parser.antlr.internal.InternalTwitterSearchParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TwitterSearchGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TwitterSearchGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
