/**
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.serializer;

import de.hub.modsoft.twittersearch.xtext.serializer.AbstractTwitterSearchSyntacticSequencer;

@SuppressWarnings("all")
public class TwitterSearchSyntacticSequencer extends AbstractTwitterSearchSyntacticSequencer {
}
