<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="twittersearch" nsURI="http://www.hu-berlin.de/modsoft/TwitterSearch/Exercise3"
    nsPrefix="twittersearch">
  <eClassifiers xsi:type="ecore:EClass" name="Search">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TwitterObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//SearchOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" eType="#//Fields"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TwitterObjectType">
    <eLiterals name="tweet"/>
    <eLiterals name="user" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fields">
    <eLiterals name="favorits" value="1"/>
    <eLiterals name="retweets" value="2"/>
    <eLiterals name="mentions" value="3"/>
    <eLiterals name="hasURL" value="5"/>
    <eLiterals name="hasImage" value="6"/>
    <eLiterals name="tweets" value="4"/>
    <eLiterals name="followerCount" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntCondition" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//IntOperators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchOption" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Keywords" eSuperTypes="#//SearchOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//SearchOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusUnit" eType="#//DistanceUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DistanceUnit">
    <eLiterals name="miles"/>
    <eLiterals name="kilometers" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntOperators">
    <eLiterals name="gt" literal=">"/>
    <eLiterals name="gte" value="1" literal=">="/>
    <eLiterals name="eq" value="2" literal="="/>
    <eLiterals name="lt" value="3" literal="&lt;"/>
    <eLiterals name="lte" value="4" literal="&lt;="/>
  </eClassifiers>
</ecore:EPackage>
