/**
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.ui.contentassist;

import de.hub.modsoft.twittersearch.xtext.ui.contentassist.AbstractTwitterSearchProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TwitterSearchProposalProvider extends AbstractTwitterSearchProposalProvider {
}
