/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TwitterSearchUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.hub.modsoft.twittersearch.xtext.ui.internal.TwitterSearchActivator.getInstance().getInjector("de.hub.modsoft.twittersearch.xtext.TwitterSearch");
	}
	
}
