/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TwitterSearchUiModule extends de.hub.modsoft.twittersearch.xtext.ui.AbstractTwitterSearchUiModule {
	public TwitterSearchUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
