/**
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.serializer;

import de.hub.modsoft.twittersearch.xtext.serializer.AbstractTwitterSearchSemanticSequencer;

@SuppressWarnings("all")
public class TwitterSearchSemanticSequencer extends AbstractTwitterSearchSemanticSequencer {
}
