<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="twittersearch" nsURI="http://www.hu-berlin.de/modsoft/TwitterSearch/1.0alt"
    nsPrefix="twittersearch">
  <eClassifiers xsi:type="ecore:EClass" name="Search">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TwitterObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="before" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="after" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" upperBound="-1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortation" eType="#//FieldExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldExpr">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TwitterObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="field" eType="#//Fields"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="field" lowerBound="1" eType="#//FieldExpr"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TwitterObjectType">
    <eLiterals name="tweet"/>
    <eLiterals name="user" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Fields">
    <eLiterals name="hashtags"/>
    <eLiterals name="favorits" value="1"/>
    <eLiterals name="retweets" value="2"/>
    <eLiterals name="mentions" value="3"/>
    <eLiterals name="tweets" value="4"/>
    <eLiterals name="hasURL" value="5"/>
    <eLiterals name="hasImage" value="6"/>
    <eLiterals name="followers" value="7"/>
    <eLiterals name="message" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringCondition" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntCondition" eSuperTypes="#//Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Location" instanceClassName="de.hub.modsoft.twittersearch.data.Location"/>
</ecore:EPackage>
