/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TwitterSearchRuntimeModule extends de.hub.modsoft.twittersearch.xtext.AbstractTwitterSearchRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return TwitterValueConverterService.class;
    }
}
