/*
 * generated by Xtext
 */
package de.hub.modsoft.twittersearch.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTwitterSearchValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.hu-berlin.de/modsoft/TwitterSearch/Exercise5"));
		return result;
	}
}
